server:
  port: 8081

spring:
  application:
    name: recipe-service
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
  datasource:
    url: jdbc:mysql://mysql:3306/recipedb
    username: recipeuser
    password: recipepass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
    enabled: true

app:
  jwt:
    secret: verylongsecretkeythatshouldbeatleast32charactersormoretobemoresecure

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html