server:
  port: 8761

spring:
  application:
    name: discovery-service
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true

eureka:
  instance:
    hostname: discovery-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always